baseURL = "/"
languageCode = "en-us"
theme = "infinity-hugo"
themesDir = "themes"
title = "Inniti Software"
[params.about]
description = "The core of our company is composed of senior analysts with extensive experience in the IT market, that support a wide range of skills needed for the development of next generation systems.\nOur team is always concerned with providing quality solutions, listening and understanding the real needs of our customers, using lean software principles such as: Eliminate Waste, Build Quality In and Create Knowledge."
enable = true
heading = "Inniti software is a young and dynamic development company based on a team of experienced specialists."
[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[params.contact]
enable = true
subtitle = "Need a solution and believe we can help you? Contact us and let's have a coffee (:"
title = "Get In Touch"
[params.cta]
bg = "images/call-to-action.jpg"
enable = false
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
title = "Subscribe to our mailing list"
[params.hero]
bg = "images/header-bg.webp"
btnText = "Discover"
countdownDay = 31
countdownMonth = "08"
countdownYear = 2019
enable = true
subtitle = "Focus on quality without waste."
title = "INNITI SOFTWARE"
[params.navigation]
about = "About"
contact = "Contact"
home = "Home"
logo = "images/logo.png"
service = "Services"
[params.service]
enable = true
subtitle = "We are ready to develop a great solution to meet your needs."
title = "Find Better Solutions Build Better Products"
[[params.service.serviceItem]]
delay = "0s"
description = "It is your content on the internet through hot sites, blogs and pages to reach your audience."
icon = "tf-globe"
title = "Website"
[[params.service.serviceItem]]
delay = "0.2s"
description = "Receive, provide and process information quickly and smartly."
icon = "tf-gears"
title = "Web System"
[[params.service.serviceItem]]
delay = "0.4s"
description = "Your system wherever your customer is via mobile devices."
icon = "tf-mobile"
title = "Mobile App"
[[params.service.serviceItem]]
delay = "0.6s"
description = " Integrate your system with other services and enjoy the best tools."
icon = "tf-ion-cloud"
title = "Backend Services"
