baseURL = "/"
languageCode = "en-us"
theme = "infinity-hugo"
themesDir = "themes"
title = "Inniti Software"
[params.about]
description = "\nThe core of our company is composed of senior analysts with extensive experience in the IT market, that support a wide range of skills needed for the development of next generation systems.\nOur team is always concerned with providing quality solutions, listening and understanding the real needs of our customers, using lean software principles such as: Eliminate Waste, Build Quality In and Create Knowledge."
enable = true
heading = "Inniti software is a young and dynamic development company based on a team of experienced specialists."
[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[params.contact]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
title = "Get In Touch"
[params.cta]
bg = "images/call-to-action.jpg"
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
title = "Subscribe to our mailing list"
[params.hero]
bg = "images/header-bg.webp"
btnText = "Discover"
countdownDay = 31
countdownMonth = "08"
countdownYear = 2019
enable = true
subtitle = "Focus on quality without waste."
title = "INNITI SOFTWARE"
[params.navigation]
about = "About"
contact = "Contact"
home = "Home"
logo = "images/logo.png"
service = "Services"
[params.service]
enable = true
subtitle = "We are ready to develop a great solution to meet your needs."
title = "Find Better Solutions Build Better Products"
[[params.service.serviceItem]]
delay = "0s"
description = "It is your content on the internet through hot sites, blogs and pages to reach your audience."
icon = "tf-strategy"
title = "Website"
[[params.service.serviceItem]]
delay = "0.2s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-circle-compass"
title = "Web System"
[[params.service.serviceItem]]
delay = "0.4s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Mobile App"
[[params.service.serviceItem]]
delay = "0.6s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-globe"
title = "Backend Services"
